// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEIW7GUVecrRsrAMBetmQLUP-G4iN0mJs',
    appId: '1:666643783238:web:968e58819244b88b927447',
    messagingSenderId: '666643783238',
    projectId: 'simple-ecom-1e5fc',
    authDomain: 'simple-ecom-1e5fc.firebaseapp.com',
    storageBucket: 'simple-ecom-1e5fc.appspot.com',
    measurementId: 'G-EYH7N1LKFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9pcwr7pfPUOhTue0hVzFWA8YtGXF5eGQ',
    appId: '1:666643783238:android:382234f82bf201b1927447',
    messagingSenderId: '666643783238',
    projectId: 'simple-ecom-1e5fc',
    storageBucket: 'simple-ecom-1e5fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA69uIJ_l5EGckfh-O9PVdbtXCTmiCcohA',
    appId: '1:666643783238:ios:48add1fd5f4fb7b8927447',
    messagingSenderId: '666643783238',
    projectId: 'simple-ecom-1e5fc',
    storageBucket: 'simple-ecom-1e5fc.appspot.com',
    iosBundleId: 'com.simple.notes.notes',
  );
}
